services:
  aistack-selection-ui:
    image: bigbrother1969/selection-ui:0.2
    container_name: aistack-selection-ui
    # Build is disabled until Docker buildx is upgraded.
    # Image must be built manually with:
    # docker build -f Dockerfile.selection-ui -t aistack-selection-ui:latest .
    ports:
      - "8181:8181"
    volumes:
      - /media/TechData:/media/TechData
    env_file:
      - .env.selection-ui
    environment:
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
