from aistack.integrity.checks.reference_integrity import (
    ReferenceIntegrityCheck,
)


def test_the_published_heritage_resolves_every_reference(projection):
    """
    Every `relations: references:` in this repository designates
    an artifact this repository declares.

    The projection is regenerated by the `projection` fixture,
    and that is the point — see its docstring for the defect that
    put it there, and for the `if not exists: return` that let an
    earlier version pass while verifying nothing.
    """

    findings = ReferenceIntegrityCheck().evaluate(projection)

    assert findings == [], [f.subjects for f in findings]
