from aistack.contracts.readme_exporter import (
    ReadmeExporter,
)


class ReadmeBundleExporter(
    ReadmeExporter
):
    """
    Generate README for Context Bundle delivery.
    """

    def export(self) -> str:

        return """# AIStack Context Bundle

This archive contains governed AIStack knowledge artifacts.

The bundle is generated from a validated AIStack knowledge repository.

Contents:

- README.md
- bundle.json
- bundle.md
- manifest.json

The bundle is portable and can be imported as a knowledge source.

Generated by AIStack.
"""
