"""
Project recorded collection gaps into the graph — `ADR-0011` § 9
(R11), cadrage 2026-09-28 (the owner's own decision: build the shared
mechanism before stacking three more 1.5 monitors on the same gap
`docker_events_monitor` already had).

**A separate function, not folded into any one stream's own
projector.** A collection gap belongs to whichever stream stopped and
resumed, but its own record lives under a dedicated root
(`aistack.generators.collection_gap.record_collection_gap`'s own
`generated_dir / "collection-gaps" / <stream_stem>`), one subdirectory
per stream — a monitor's gap history is not part of that stream's own
observation history, the same reasoning `project_docker_events`
already gives for living off `project_observation_history`'s own root.

**Reuses `stream_iri`, not a new activity per stream.** A collection
gap for `"docker-events"` is generated by that same
`urn:aistack:stream:docker-events` activity `project_docker_events`
already creates when it sees its first batch — this module never
creates a second, competing activity node for a stream another
projector already owns; it only ever links to the one that exists (or
will, once that stream's own projector runs in the same rebuild pass).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from aistack.history import format_instant, latest_observations
from aistack.timemachine.graph import GraphStore, Literal
from aistack.timemachine.iri import collection_gap_iri, stream_iri
from aistack.timemachine.projection.filter import filter_fact
from aistack.timemachine.vocabulary import (
    AISTACK_COLLECTION_GAP,
    AISTACK_OCCURRED_AT,
    AISTACK_STABLE_SUBJECT,
    PROV_ENTITY,
    PROV_GENERATED_AT_TIME,
    PROV_WAS_GENERATED_BY,
    RDF_TYPE,
    XSD_DATE_TIME,
)

# `aistack.generators.collection_gap.DEFAULT_COLLECTION_GAPS_ROOT`'s
# own leaf name, redeclared here the same way `docker_events.STEM`
# redeclares `"docker-events"` rather than importing across the
# writer/reader boundary each collector-facing module already keeps.
COLLECTION_GAPS_DIRNAME = "collection-gaps"

# The one file stem `record_collection_gap` writes under each stream's
# own subdirectory — `"collection-gap.json"`, singular, one gap per
# historicised write (a stream that gaps and resumes twice gets two
# history files, not one file holding two).
STEM = "collection-gap"


@dataclass(frozen=True)
class CollectionGapsProjectionSummary:
    """What one `project_collection_gaps` run actually did — the same
    measured-report shape every other stream's projection already
    gives a caller."""

    streams_seen: int
    gaps_seen: int
    facts_written: int
    facts_dropped: int


def project_collection_gaps(
    store: GraphStore,
    generated_dir: Path = Path("reports/generated"),
    user_data_roots: Iterable[str] = (),
) -> CollectionGapsProjectionSummary:
    """
    Add every recorded collection gap under
    `generated_dir / "collection-gaps"` to `store` — one subdirectory
    per stream, each walked the same way `project_docker_events`
    already walks its own dedicated root.

    For each recorded gap: it exists (`prov:Entity`), which stream it
    belongs to (`aistack:stableSubject`, the stream's own stem —
    `ADR-0011` § 9's own "a subject" — since this first cut records
    gaps at the whole-collector level, not per tracked container;
    narrower gap subjects are a future refinement, not invented here),
    which stream's activity generated it (`prov:wasGeneratedBy`,
    reusing that stream's own `stream_iri` — never a second activity
    node), when the gap began (`aistack:occurredAt` — the real-world
    instant coverage was lost) and when this fact was recorded, which
    is also the instant coverage resumed (`prov:generatedAtTime` —
    `record_collection_gap`'s own docstring: a gap fact can only ever
    be written once resumption has already happened, so its recording
    time and its end are the same instant), and, on the stream's own
    activity node, `aistack:collectionGap` pointing at this gap
    entity — `ADR-0011` § 9's own reserved predicate, its first real
    writer.
    """

    gaps_root = generated_dir / COLLECTION_GAPS_DIRNAME

    streams_seen = 0
    gaps_seen = 0
    facts_written = 0
    facts_dropped = 0

    def emit(subject: str, predicate: str, obj: str | Literal) -> None:
        nonlocal facts_written, facts_dropped
        if filter_fact(subject, obj, user_data_roots):
            store.add(subject, predicate, obj)
            facts_written += 1
        else:
            facts_dropped += 1

    if not gaps_root.is_dir():
        return CollectionGapsProjectionSummary(0, 0, 0, 0)

    for stream_dir in sorted(path for path in gaps_root.iterdir() if path.is_dir()):
        stream_stem_name = stream_dir.name
        activity = stream_iri(stream_stem_name)
        streams_seen += 1

        for observation in latest_observations(stream_dir, STEM):
            instant = observation.observed_at

            parsed = json.loads(observation.read())
            if not isinstance(parsed, dict):
                continue
            start = parsed.get("start")
            if not isinstance(start, str):
                continue

            gaps_seen += 1
            instant_label = format_instant(instant)
            gap_entity = collection_gap_iri(stream_stem_name, instant_label)

            emit(gap_entity, RDF_TYPE, PROV_ENTITY)
            emit(gap_entity, PROV_WAS_GENERATED_BY, activity)
            emit(
                gap_entity,
                PROV_GENERATED_AT_TIME,
                Literal(instant.isoformat(), datatype=XSD_DATE_TIME),
            )
            emit(gap_entity, AISTACK_OCCURRED_AT, Literal(start, datatype=XSD_DATE_TIME))
            emit(gap_entity, AISTACK_STABLE_SUBJECT, Literal(stream_stem_name))
            emit(activity, AISTACK_COLLECTION_GAP, gap_entity)

    return CollectionGapsProjectionSummary(
        streams_seen=streams_seen,
        gaps_seen=gaps_seen,
        facts_written=facts_written,
        facts_dropped=facts_dropped,
    )
