"""
Project the dock's governed changes into the graph (1.10, `ADR-0019`
§ 6): one `prov:Activity` per executed proposal
(`dock_change_iri(<proposal>)`), from `generated_dir/dock/proposals/`.

For each change that ended — `applied`, `rolled_back` or `failed`,
after the dock took it:

- when it started and ended (`prov:startedAtTime`/`prov:endedAtTime`:
  its first operation's start, the event that set its final state) and
  how it ended (`aistack:changeOutcome`);
- who stands behind it (`prov:wasAssociatedWith`): the person who
  proposed it, the one who validated it, and the dock agent that
  executed it;
- per image changed, a `prov:Entity` generated by the change, naming
  the container's stable subject — the same `aistack:stableSubject` the
  image-digest observations carry — and the digest before and after;
- its why (`prov:used`): the explication the dock recorded for it
  (`aistack.dock.explication`, `metadata.dock_proposal`).

A proposal never executed (proposed, validated, rejected) is a
decision, not yet an activity: not projected.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from aistack.dock import proposals as store
from aistack.dock.explication import change_subject
from aistack.explications.human import person_source
from aistack.history import available_stems, every_version
from aistack.history.subject_names import subject_for_stem
from aistack.timemachine.graph import GraphStore, Literal
from aistack.timemachine.iri import agent_iri, dock_change_iri, explication_iri
from aistack.timemachine.projection.filter import filter_fact
from aistack.timemachine.vocabulary import (
    AISTACK_CHANGE_OUTCOME,
    AISTACK_IMAGE_DIGEST,
    AISTACK_PREVIOUS_DIGEST,
    AISTACK_STABLE_SUBJECT,
    PROV_ACTIVITY,
    PROV_AGENT,
    PROV_ENDED_AT_TIME,
    PROV_ENTITY,
    PROV_STARTED_AT_TIME,
    PROV_USED,
    PROV_WAS_ASSOCIATED_WITH,
    PROV_WAS_GENERATED_BY,
    RDF_TYPE,
    XSD_DATE_TIME,
)

ENDED = (store.APPLIED, store.ROLLED_BACK, store.FAILED)
DOCK_AGENT = "dock"


@dataclass(frozen=True)
class DockChangeProjectionSummary:
    changes_seen: int
    facts_written: int
    facts_dropped: int


def _explications_of(explications_dir: Path) -> dict[str, list[tuple[str, str]]]:
    """Proposal id → [(subject, instant label)] of the explications
    the dock recorded for it."""

    found: dict[str, list[tuple[str, str]]] = {}
    for stem in available_stems(explications_dir):
        subject = subject_for_stem(stem)
        for observation in every_version(explications_dir, stem):
            try:
                metadata = json.loads(observation.read()).get("metadata") or {}
            except (OSError, ValueError, AttributeError):
                continue
            proposal = metadata.get("dock_proposal")
            if proposal:
                found.setdefault(str(proposal), []).append((subject, observation.label))
    return found


def project_dock_changes(
    store_: GraphStore,
    generated_dir: Path = Path("reports/generated"),
    user_data_roots: Iterable[str] = (),
) -> DockChangeProjectionSummary:
    changes_seen = 0
    facts_written = 0
    facts_dropped = 0

    def emit(subject: str, predicate: str, obj: str | Literal) -> None:
        nonlocal facts_written, facts_dropped
        if filter_fact(subject, obj, user_data_roots):
            store_.add(subject, predicate, obj)
            facts_written += 1
        else:
            facts_dropped += 1

    def agent(name: str) -> str:
        iri = agent_iri(name)
        emit(iri, RDF_TYPE, PROV_AGENT)
        return iri

    whys = _explications_of(generated_dir / "explications")
    for proposal in store.all_proposals(generated_dir):
        if proposal.status not in ENDED or not proposal.operations:
            continue
        changes_seen += 1
        activity = dock_change_iri(proposal.id)
        emit(activity, RDF_TYPE, PROV_ACTIVITY)
        started = proposal.operations[0].get("started_at")
        if started:
            emit(activity, PROV_STARTED_AT_TIME, Literal(str(started), datatype=XSD_DATE_TIME))
        ended = next((h["at"] for h in reversed(proposal.history) if h["event"] == proposal.status), "")
        if ended:
            emit(activity, PROV_ENDED_AT_TIME, Literal(ended, datatype=XSD_DATE_TIME))
        emit(activity, AISTACK_CHANGE_OUTCOME, Literal(proposal.status))

        emit(activity, PROV_WAS_ASSOCIATED_WITH, agent(person_source(proposal.proposed_by)))
        if proposal.decided_by and proposal.decided_by != proposal.proposed_by:
            emit(activity, PROV_WAS_ASSOCIATED_WITH, agent(person_source(proposal.decided_by)))
        emit(activity, PROV_WAS_ASSOCIATED_WITH, agent(DOCK_AGENT))

        for change in proposal.changes:
            image = dock_change_iri(proposal.id, change.container)
            emit(image, RDF_TYPE, PROV_ENTITY)
            emit(image, PROV_WAS_GENERATED_BY, activity)
            emit(image, AISTACK_STABLE_SUBJECT, Literal(change_subject(change)))
            emit(image, AISTACK_PREVIOUS_DIGEST, Literal(change.from_digest))
            emit(image, AISTACK_IMAGE_DIGEST, Literal(change.to_digest))

        for subject, label in whys.get(proposal.id, []):
            emit(activity, PROV_USED, explication_iri(subject, label))

    return DockChangeProjectionSummary(
        changes_seen=changes_seen, facts_written=facts_written, facts_dropped=facts_dropped,
    )
