"""
Project the dock's governed changes into the graph (1.10, `ADR-0019`
§ 6): one stream, `dock`, and one `prov:Entity` per executed proposal
(`dock_change_iri(<proposal>)`), from `generated_dir/dock/proposals/`,
so a change sits on the Time Machine's ribbon like any other record.

For each change that ended — `applied`, `rolled_back` or `failed`,
after the dock took it:

- generated by the `dock` stream when it ended
  (`prov:generatedAtTime`, the event that set its final state), with
  when it started (`prov:startedAtTime`, its first operation) and how
  it ended (`aistack:changeOutcome`);
- who stands behind it (`prov:wasAttributedTo`): the person who
  proposed it, the one who validated it, and the dock agent that
  executed it;
- per image changed, a `prov:Entity` part of the change
  (`aistack:partOf`), at the same instant, naming the container's
  stable subject — the same `aistack:stableSubject` the image-digest
  observations carry — and the digest before and after;
- its why (`prov:wasDerivedFrom`): the explication the dock recorded
  for it (`aistack.dock.explication`, `metadata.dock_proposal`).

A proposal never executed (proposed, validated, rejected) is a
decision, not yet a change: not projected.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from aistack.dock import proposals as store
from aistack.dock.explication import change_subject
from aistack.explications.human import person_source
from aistack.history import available_stems, every_version
from aistack.history.subject_names import subject_for_stem
from aistack.timemachine.graph import GraphStore, Literal
from aistack.timemachine.iri import agent_iri, dock_change_iri, explication_iri, stream_iri
from aistack.timemachine.projection.filter import filter_fact
from aistack.timemachine.vocabulary import (
    AISTACK_CHANGE_OUTCOME,
    AISTACK_IMAGE_DIGEST,
    AISTACK_PREVIOUS_DIGEST,
    AISTACK_STABLE_SUBJECT,
    AISTACK_PART_OF,
    PROV_ACTIVITY,
    PROV_AGENT,
    PROV_ENTITY,
    PROV_GENERATED_AT_TIME,
    PROV_STARTED_AT_TIME,
    PROV_WAS_ATTRIBUTED_TO,
    PROV_WAS_DERIVED_FROM,
    PROV_WAS_GENERATED_BY,
    RDF_TYPE,
    XSD_DATE_TIME,
)

ENDED = (store.APPLIED, store.ROLLED_BACK, store.FAILED)
DOCK_AGENT = "dock"
STEM = "dock"


@dataclass(frozen=True)
class DockChangeProjectionSummary:
    changes_seen: int
    facts_written: int
    facts_dropped: int


def _explications_of(explications_dir: Path) -> dict[str, list[tuple[str, str]]]:
    """Proposal id → [(subject, instant label)] of the explications
    the dock recorded for it."""

    found: dict[str, list[tuple[str, str]]] = {}
    for stem in available_stems(explications_dir):
        subject = subject_for_stem(stem)
        for observation in every_version(explications_dir, stem):
            try:
                metadata = json.loads(observation.read()).get("metadata") or {}
            except (OSError, ValueError, AttributeError):
                continue
            proposal = metadata.get("dock_proposal")
            if proposal:
                found.setdefault(str(proposal), []).append((subject, observation.label))
    return found


def project_dock_changes(
    store_: GraphStore,
    generated_dir: Path = Path("reports/generated"),
    user_data_roots: Iterable[str] = (),
) -> DockChangeProjectionSummary:
    changes_seen = 0
    facts_written = 0
    facts_dropped = 0

    def emit(subject: str, predicate: str, obj: str | Literal) -> None:
        nonlocal facts_written, facts_dropped
        if filter_fact(subject, obj, user_data_roots):
            store_.add(subject, predicate, obj)
            facts_written += 1
        else:
            facts_dropped += 1

    def agent(name: str) -> str:
        iri = agent_iri(name)
        emit(iri, RDF_TYPE, PROV_AGENT)
        return iri

    whys = _explications_of(generated_dir / "explications")
    stream = stream_iri(STEM)
    for proposal in store.all_proposals(generated_dir):
        if proposal.status not in ENDED or not proposal.operations:
            continue
        ended = next((h["at"] for h in reversed(proposal.history) if h["event"] == proposal.status), "")
        if not ended:
            continue
        if changes_seen == 0:
            emit(stream, RDF_TYPE, PROV_ACTIVITY)
        changes_seen += 1
        change = dock_change_iri(proposal.id)
        at = Literal(ended, datatype=XSD_DATE_TIME)
        emit(change, RDF_TYPE, PROV_ENTITY)
        emit(change, PROV_WAS_GENERATED_BY, stream)
        emit(change, PROV_GENERATED_AT_TIME, at)
        started = proposal.operations[0].get("started_at")
        if started:
            emit(change, PROV_STARTED_AT_TIME, Literal(str(started), datatype=XSD_DATE_TIME))
        emit(change, AISTACK_CHANGE_OUTCOME, Literal(proposal.status))
        emit(change, AISTACK_STABLE_SUBJECT, Literal(proposal.service))

        emit(change, PROV_WAS_ATTRIBUTED_TO, agent(person_source(proposal.proposed_by)))
        if proposal.decided_by and proposal.decided_by != proposal.proposed_by:
            emit(change, PROV_WAS_ATTRIBUTED_TO, agent(person_source(proposal.decided_by)))
        emit(change, PROV_WAS_ATTRIBUTED_TO, agent(DOCK_AGENT))

        for item in proposal.changes:
            image = dock_change_iri(proposal.id, item.container)
            emit(image, RDF_TYPE, PROV_ENTITY)
            emit(image, PROV_WAS_GENERATED_BY, stream)
            emit(image, PROV_GENERATED_AT_TIME, at)
            emit(image, AISTACK_PART_OF, change)
            emit(image, AISTACK_STABLE_SUBJECT, Literal(change_subject(item)))
            emit(image, AISTACK_PREVIOUS_DIGEST, Literal(item.from_digest))
            emit(image, AISTACK_IMAGE_DIGEST, Literal(item.to_digest))

        for subject, label in whys.get(proposal.id, []):
            emit(change, PROV_WAS_DERIVED_FROM, explication_iri(subject, label))

    return DockChangeProjectionSummary(
        changes_seen=changes_seen, facts_written=facts_written, facts_dropped=facts_dropped,
    )
