"""
Project what changes on the hosts into the graph (1.11, `ADR-0020`
§ 7): one stream per host (`host-<name>`), one `prov:Entity` per event
its collector recorded — a package installed or upgraded, an apt run, a
file added, removed or modified, a unit enabled or disabled, the first
run's baseline.

Each event: generated by its host's stream at the instant the event
says (the log's own time for packages), its subject
(`aistack:stableSubject`: `<host>/package/<name>`, `<host>:<path>`,
`<host>/unit/<unit>`, `<host>/apt`, `<host>`), its kind, its action,
and a short detail — versions, states, a command line, a size — never a
file's fingerprint or content.

A host whose records cannot be read is counted, not projected: what it
did is not lost, only not visible until its directory is back.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable

from aistack.hosts.records import HostRecords
from aistack.timemachine.graph import GraphStore, Literal
from aistack.timemachine.iri import host_event_iri, stream_iri
from aistack.timemachine.projection.filter import filter_fact
from aistack.timemachine.vocabulary import (
    AISTACK_HOST_ACTION,
    AISTACK_HOST_DETAIL,
    AISTACK_HOST_EVENT_KIND,
    AISTACK_STABLE_SUBJECT,
    PROV_ACTIVITY,
    PROV_ENTITY,
    PROV_GENERATED_AT_TIME,
    PROV_WAS_GENERATED_BY,
    RDF_TYPE,
    XSD_DATE_TIME,
)

STEM_PREFIX = "host-"


def stem_of(host: str) -> str:
    return f"{STEM_PREFIX}{host}"


@dataclass(frozen=True)
class HostChangesProjectionSummary:
    hosts_seen: int
    hosts_unreadable: int
    events_seen: int
    facts_written: int
    facts_dropped: int


def describe_event(host: str, event: dict[str, Any]) -> tuple[str, str, str]:
    """(subject, action, detail) of one event — what the graph keeps."""

    kind = str(event.get("kind", ""))
    if kind == "package":
        name = str(event.get("package", "")).split(":", 1)[0]
        before, after = event.get("from"), event.get("to")
        detail = f"{before or '∅'} → {after or '∅'}"
        return f"{host}/package/{name}", str(event.get("action", "")), detail
    if kind == "apt":
        counts = event.get("counts") or {}
        detail = ", ".join(f"{action} {count}" for action, count in sorted(counts.items()))
        command = str(event.get("commandline", ""))
        return f"{host}/apt", "run", f"{command} ({detail})" if detail else command
    if kind == "file":
        before, after = event.get("before") or {}, event.get("after") or {}
        changed = sorted(
            key for key in set(before) | set(after) if key != "fp" and before.get(key) != after.get(key)
        )
        if before.get("fp") != after.get("fp") and before and after:
            changed.append("content")
        detail = ", ".join(changed) if event.get("action") == "modified" else ""
        return f"{host}:{event.get('path', '')}", str(event.get("action", "")), detail
    if kind == "unit":
        return f"{host}/unit/{event.get('unit', '')}", str(event.get("after") or "removed"), (
            f"{event.get('before') or '∅'} → {event.get('after') or '∅'}"
        )
    if kind == "baseline":
        return host, "baseline", f"{event.get('files', 0)} files, {event.get('units', 0)} units"
    return host, kind, ""


def project_host_changes(
    store: GraphStore,
    hosts: Iterable[HostRecords],
    user_data_roots: Iterable[str] = (),
) -> HostChangesProjectionSummary:
    hosts_seen = hosts_unreadable = events_seen = facts_written = facts_dropped = 0

    def emit(subject: str, predicate: str, obj: str | Literal) -> None:
        nonlocal facts_written, facts_dropped
        if filter_fact(subject, obj, user_data_roots):
            store.add(subject, predicate, obj)
            facts_written += 1
        else:
            facts_dropped += 1

    for records in hosts:
        hosts_seen += 1
        if records.problem and not records.events:
            hosts_unreadable += 1
            continue
        if not records.events:
            continue
        activity = stream_iri(stem_of(records.host))
        emit(activity, RDF_TYPE, PROV_ACTIVITY)
        for line, event in records.events:
            events_seen += 1
            entity = host_event_iri(records.host, line)
            subject, action, detail = describe_event(records.host, event)
            emit(entity, RDF_TYPE, PROV_ENTITY)
            emit(entity, PROV_WAS_GENERATED_BY, activity)
            emit(entity, PROV_GENERATED_AT_TIME, Literal(str(event["at"]), datatype=XSD_DATE_TIME))
            emit(entity, AISTACK_STABLE_SUBJECT, Literal(subject))
            emit(entity, AISTACK_HOST_EVENT_KIND, Literal(str(event.get("kind", ""))))
            if action:
                emit(entity, AISTACK_HOST_ACTION, Literal(action))
            if detail:
                emit(entity, AISTACK_HOST_DETAIL, Literal(detail))

    return HostChangesProjectionSummary(hosts_seen, hosts_unreadable, events_seen, facts_written, facts_dropped)
